<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c2a935a6-23fa-4668-a4c9-c5b1b6f1b83e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelTravel.Application\HotelTravel.Application.csproj" />
    <ProjectReference Include="..\HotelTravel.Infrastructure\HotelTravel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
